# Generated by Django 3.1 on 2020-08-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_auto_20200811_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='property',
            field=models.CharField(default='', max_length=20),
        ),
    ]
