# Generated by Django 3.1 on 2020-08-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_auto_20200811_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='name',
            new_name='attribute',
        ),
        migrations.RemoveField(
            model_name='product',
            name='attribute',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eshop.product'),
        ),
    ]
