# Generated by Django 3.1 on 2020-08-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_auto_20200811_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='attribute',
            new_name='name',
        ),
    ]
