# Generated by Django 3.0.8 on 2020-08-20 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0011_auto_20200820_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gallery',
        ),
        migrations.AddField(
            model_name='gallery',
            name='productid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop.Product'),
        ),
    ]
