# Generated by Django 3.0.8 on 2020-08-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0016_auto_20200822_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='instructions',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
