# Generated by Django 3.0.8 on 2020-08-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0017_auto_20200825_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=200, null=True),
        ),
    ]
