# Generated by Django 3.1 on 2020-09-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0019_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordering', 'Ordering'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered')], default='Ordering', max_length=200, null=True),
        ),
    ]
