# Generated by Django 3.1 on 2020-09-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0025_auto_20200908_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
