# Generated by Django 3.1 on 2020-09-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0027_order_charge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordering', 'Ordering'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Ordering', max_length=200, null=True),
        ),
    ]
