# Generated by Django 3.1 on 2020-09-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0028_auto_20200911_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordering', 'Ordering'), ('Checkout', 'Checkout'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Ordering', max_length=200, null=True),
        ),
    ]
