# Generated by Django 3.1 on 2020-09-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0029_auto_20200915_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
