# Generated by Django 3.1 on 2020-09-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0030_auto_20200915_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('prefix', models.CharField(max_length=200)),
                ('suffix', models.CharField(max_length=200)),
                ('fontawesome_icon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_src', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
