# Generated by Django 3.1 on 2020-09-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0031_footercontactinfo_homepagebanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagebanner',
            name='image_src',
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
