# Generated by Django 3.1 on 2020-09-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0032_auto_20200915_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image4',
        ),
    ]
